"""Initial migration: Tabelle EventHub

Revision ID: 4657c8c46373
Revises: 
Create Date: 2026-05-23 13:43:02.249825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4657c8c46373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('max_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('organizer_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_registrations',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_scope_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clscope_attrs'))

    op.drop_table('client_scope_attributes')
    with op.batch_alter_table('user_federation_mapper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_usr_fed_map_fed_prv'))
        batch_op.drop_index(batch_op.f('idx_usr_fed_map_realm'))

    op.drop_table('user_federation_mapper')
    op.drop_table('databasechangeloglock')
    op.drop_table('user_federation_config')
    op.drop_table('authenticator_config_entry')
    op.drop_table('client_user_session_note')
    op.drop_table('client_session_prot_mapper')
    with op.batch_alter_table('authentication_flow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_auth_flow_realm'))

    op.drop_table('authentication_flow')
    with op.batch_alter_table('user_required_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_reqactions'))

    op.drop_table('user_required_action')
    with op.batch_alter_table('associated_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_assoc_pol_assoc_pol_id'))

    op.drop_table('associated_policy')
    op.drop_table('resource_server_perm_ticket')
    op.drop_table('client_session_role')
    with op.batch_alter_table('client_initial_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_client_init_acc_realm'))

    op.drop_table('client_initial_access')
    op.drop_table('username_login_failure')
    op.drop_table('resource_attribute')
    with op.batch_alter_table('client_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_realm_clscope'))

    op.drop_table('client_scope')
    op.drop_table('realm_required_credential')
    with op.batch_alter_table('client_scope_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cl_clscope'))
        batch_op.drop_index(batch_op.f('idx_clscope_cl'))

    op.drop_table('client_scope_client')
    with op.batch_alter_table('resource_server_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_res_srv_scope_res_srv'))

    op.drop_table('resource_server_scope')
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_consent'))

    op.drop_table('user_consent')
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_credential'))

    op.drop_table('credential')
    with op.batch_alter_table('identity_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ident_prov_realm'))

    op.drop_table('identity_provider')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_client_id'))

    op.drop_table('client')
    with op.batch_alter_table('scope_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scope_mapping_role'))

    op.drop_table('scope_mapping')
    with op.batch_alter_table('fed_user_role_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fu_role_mapping'))
        batch_op.drop_index(batch_op.f('idx_fu_role_mapping_ru'))

    op.drop_table('fed_user_role_mapping')
    with op.batch_alter_table('user_group_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_group_mapping'))

    op.drop_table('user_group_membership')
    with op.batch_alter_table('component_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_compo_config_compo'))

    op.drop_table('component_config')
    with op.batch_alter_table('resource_server_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_res_srv_res_res_srv'))

    op.drop_table('resource_server_resource')
    op.drop_table('broker_link')
    op.drop_table('keycloak_group')
    with op.batch_alter_table('realm_enabled_event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_realm_evt_types_realm'))

    op.drop_table('realm_enabled_event_types')
    op.drop_table('resource_server')
    with op.batch_alter_table('resource_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_res_scope_scope'))

    op.drop_table('resource_scope')
    op.drop_table('fed_user_consent_cl_scope')
    op.drop_table('client_auth_flow_bindings')
    op.drop_table('client_node_registrations')
    with op.batch_alter_table('admin_event_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_admin_event_time'))

    op.drop_table('admin_event_entity')
    op.drop_table('realm_localizations')
    with op.batch_alter_table('client_scope_role_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clscope_role'))
        batch_op.drop_index(batch_op.f('idx_role_clscope'))

    op.drop_table('client_scope_role_mapping')
    op.drop_table('idp_mapper_config')
    op.drop_table('client_session_auth_status')
    with op.batch_alter_table('realm_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_realm_attr_realm'))

    op.drop_table('realm_attribute')
    op.drop_table('identity_provider_config')
    with op.batch_alter_table('offline_client_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_offline_css_preload'))
        batch_op.drop_index(batch_op.f('idx_us_sess_id_on_cl_sess'))

    op.drop_table('offline_client_session')
    with op.batch_alter_table('realm_default_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_realm_def_grp_realm'))

    op.drop_table('realm_default_groups')
    with op.batch_alter_table('redirect_uris', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_redir_uri_client'))

    op.drop_table('redirect_uris')
    with op.batch_alter_table('keycloak_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_keycloak_role_client'))
        batch_op.drop_index(batch_op.f('idx_keycloak_role_realm'))

    op.drop_table('keycloak_role')
    op.drop_table('required_action_config')
    with op.batch_alter_table('identity_provider_mapper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_id_prov_mapp_realm'))

    op.drop_table('identity_provider_mapper')
    with op.batch_alter_table('user_federation_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_usr_fed_prv_realm'))

    op.drop_table('user_federation_provider')
    with op.batch_alter_table('fed_user_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fed_user_attr_long_values'))
        batch_op.drop_index(batch_op.f('fed_user_attr_long_values_lower_case'))
        batch_op.drop_index(batch_op.f('idx_fu_attribute'))

    op.drop_table('fed_user_attribute')
    with op.batch_alter_table('offline_user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_offline_uss_by_user'))
        batch_op.drop_index(batch_op.f('idx_offline_uss_by_usersess'))
        batch_op.drop_index(batch_op.f('idx_offline_uss_createdon'))
        batch_op.drop_index(batch_op.f('idx_offline_uss_preload'))

    op.drop_table('offline_user_session')
    with op.batch_alter_table('realm_events_listeners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_realm_evt_list_realm'))

    op.drop_table('realm_events_listeners')
    with op.batch_alter_table('fed_user_consent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fu_cnsnt_ext'))
        batch_op.drop_index(batch_op.f('idx_fu_consent'))
        batch_op.drop_index(batch_op.f('idx_fu_consent_ru'))

    op.drop_table('fed_user_consent')
    with op.batch_alter_table('user_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_attribute'))
        batch_op.drop_index(batch_op.f('idx_user_attribute_name'))
        batch_op.drop_index(batch_op.f('user_attr_long_values'))
        batch_op.drop_index(batch_op.f('user_attr_long_values_lower_case'))

    op.drop_table('user_attribute')
    with op.batch_alter_table('resource_server_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_res_serv_pol_res_serv'))

    op.drop_table('resource_server_policy')
    with op.batch_alter_table('realm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_realm_master_adm_cli'))

    op.drop_table('realm')
    with op.batch_alter_table('client_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_client_att_by_name_value'))

    op.drop_table('client_attributes')
    op.drop_table('resource_uris')
    op.drop_table('protocol_mapper_config')
    with op.batch_alter_table('client_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_client_session_session'))

    op.drop_table('client_session')
    op.drop_table('databasechangelog')
    with op.batch_alter_table('user_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_email'))
        batch_op.drop_index(batch_op.f('idx_user_service_account'))

    op.drop_table('user_entity')
    with op.batch_alter_table('event_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_time'))

    op.drop_table('event_entity')
    with op.batch_alter_table('resource_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_res_policy_policy'))

    op.drop_table('resource_policy')
    op.drop_table('federated_user')
    with op.batch_alter_table('fed_user_group_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fu_group_membership'))
        batch_op.drop_index(batch_op.f('idx_fu_group_membership_ru'))

    op.drop_table('fed_user_group_membership')
    with op.batch_alter_table('required_action_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_req_act_prov_realm'))

    op.drop_table('required_action_provider')
    with op.batch_alter_table('group_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_group_att_by_name_value'))
        batch_op.drop_index(batch_op.f('idx_group_attr_group'))

    op.drop_table('group_attribute')
    with op.batch_alter_table('authentication_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_auth_exec_flow'))
        batch_op.drop_index(batch_op.f('idx_auth_exec_realm_flow'))

    op.drop_table('authentication_execution')
    op.drop_table('realm_smtp_config')
    with op.batch_alter_table('user_role_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_role_mapping'))

    op.drop_table('user_role_mapping')
    with op.batch_alter_table('fed_user_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fu_credential'))
        batch_op.drop_index(batch_op.f('idx_fu_credential_ru'))

    op.drop_table('fed_user_credential')
    with op.batch_alter_table('role_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_role_attribute'))

    op.drop_table('role_attribute')
    op.drop_table('client_session_note')
    op.drop_table('user_federation_mapper_config')
    with op.batch_alter_table('federated_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fedidentity_feduser'))
        batch_op.drop_index(batch_op.f('idx_fedidentity_user'))

    op.drop_table('federated_identity')
    op.drop_table('policy_config')
    with op.batch_alter_table('realm_supported_locales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_realm_supp_local_realm'))

    op.drop_table('realm_supported_locales')
    with op.batch_alter_table('authenticator_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_auth_config_realm'))

    op.drop_table('authenticator_config')
    op.drop_table('user_session_note')
    with op.batch_alter_table('default_client_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_defcls_realm'))
        batch_op.drop_index(batch_op.f('idx_defcls_scope'))

    op.drop_table('default_client_scope')
    with op.batch_alter_table('composite_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_composite'))
        batch_op.drop_index(batch_op.f('idx_composite_child'))

    op.drop_table('composite_role')
    with op.batch_alter_table('user_consent_client_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_usconsent_clscope'))

    op.drop_table('user_consent_client_scope')
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_component_provider_type'))
        batch_op.drop_index(batch_op.f('idx_component_realm'))

    op.drop_table('component')
    with op.batch_alter_table('web_origins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_web_orig_client'))

    op.drop_table('web_origins')
    with op.batch_alter_table('group_role_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_group_role_mapp_group'))

    op.drop_table('group_role_mapping')
    with op.batch_alter_table('fed_user_required_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fu_required_action'))
        batch_op.drop_index(batch_op.f('idx_fu_required_action_ru'))

    op.drop_table('fed_user_required_action')
    op.drop_table('user_session')
    with op.batch_alter_table('protocol_mapper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clscope_protmap'))
        batch_op.drop_index(batch_op.f('idx_protocol_mapper_client'))

    op.drop_table('protocol_mapper')
    with op.batch_alter_table('scope_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scope_policy_policy'))

    op.drop_table('scope_policy')
    with op.batch_alter_table('migration_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_update_time'))

    op.drop_table('migration_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_model',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('update_time', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_migmod'))
    )
    with op.batch_alter_table('migration_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_update_time'), ['update_time'], unique=False)

    op.create_table('scope_policy',
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name=op.f('fk_frsrasp13xcx4wnkog82ssrfy')),
    sa.ForeignKeyConstraint(['scope_id'], ['resource_server_scope.id'], name=op.f('fk_frsrpass3xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('scope_id', 'policy_id', name=op.f('constraint_farsrsps'))
    )
    with op.batch_alter_table('scope_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_scope_policy_policy'), ['policy_id'], unique=False)

    op.create_table('protocol_mapper',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('protocol_mapper_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('client_scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_pcm_realm')),
    sa.ForeignKeyConstraint(['client_scope_id'], ['client_scope.id'], name=op.f('fk_cli_scope_mapper')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_pcm'))
    )
    with op.batch_alter_table('protocol_mapper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_protocol_mapper_client'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_clscope_protmap'), ['client_scope_id'], unique=False)

    op.create_table('user_session',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('auth_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_session_refresh', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('login_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('remember_me', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('started', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_session_state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('broker_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('broker_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_57'))
    )
    op.create_table('fed_user_required_action',
    sa.Column('required_action', sa.VARCHAR(length=255), server_default=sa.text("' '::character varying"), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('required_action', 'user_id', name=op.f('constr_fed_required_action'))
    )
    with op.batch_alter_table('fed_user_required_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fu_required_action_ru'), ['realm_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fu_required_action'), ['user_id', 'required_action'], unique=False)

    op.create_table('group_role_mapping',
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['keycloak_group.id'], name=op.f('fk_group_role_group')),
    sa.PrimaryKeyConstraint('role_id', 'group_id', name=op.f('constraint_group_role'))
    )
    with op.batch_alter_table('group_role_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_group_role_mapp_group'), ['group_id'], unique=False)

    op.create_table('web_origins',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_lojpho213xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('client_id', 'value', name=op.f('constraint_web_origins'))
    )
    with op.batch_alter_table('web_origins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_web_orig_client'), ['client_id'], unique=False)

    op.create_table('component',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('sub_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_component_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('constr_component_pk'))
    )
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_component_realm'), ['realm_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_component_provider_type'), ['provider_type'], unique=False)

    op.create_table('user_consent_client_scope',
    sa.Column('user_consent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_consent_id'], ['user_consent.id'], name=op.f('fk_grntcsnt_clsc_usc')),
    sa.PrimaryKeyConstraint('user_consent_id', 'scope_id', name=op.f('constraint_grntcsnt_clsc_pm'))
    )
    with op.batch_alter_table('user_consent_client_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usconsent_clscope'), ['user_consent_id'], unique=False)

    op.create_table('composite_role',
    sa.Column('composite', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('child_role', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_role'], ['keycloak_role.id'], name=op.f('fk_gr7thllb9lu8q4vqa4524jjy8')),
    sa.ForeignKeyConstraint(['composite'], ['keycloak_role.id'], name=op.f('fk_a63wvekftu8jo1pnj81e7mce2')),
    sa.PrimaryKeyConstraint('composite', 'child_role', name=op.f('constraint_composite_role'))
    )
    with op.batch_alter_table('composite_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_composite_child'), ['child_role'], unique=False)
        batch_op.create_index(batch_op.f('idx_composite'), ['composite'], unique=False)

    op.create_table('default_client_scope',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('default_scope', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_r_def_cli_scope_realm')),
    sa.PrimaryKeyConstraint('realm_id', 'scope_id', name=op.f('r_def_cli_scope_bind'))
    )
    with op.batch_alter_table('default_client_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_defcls_scope'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_defcls_realm'), ['realm_id'], unique=False)

    op.create_table('user_session_note',
    sa.Column('user_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_session'], ['user_session.id'], name=op.f('fk5edfb00ff51d3472')),
    sa.PrimaryKeyConstraint('user_session', 'name', name=op.f('constraint_usn_pk'))
    )
    op.create_table('authenticator_config',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_auth_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_auth_pk'))
    )
    with op.batch_alter_table('authenticator_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_auth_config_realm'), ['realm_id'], unique=False)

    op.create_table('realm_supported_locales',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_supported_locales_realm')),
    sa.PrimaryKeyConstraint('realm_id', 'value', name=op.f('constr_realm_supported_locales'))
    )
    with op.batch_alter_table('realm_supported_locales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_realm_supp_local_realm'), ['realm_id'], unique=False)

    op.create_table('policy_config',
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name=op.f('fkdc34197cf864c4e43')),
    sa.PrimaryKeyConstraint('policy_id', 'name', name=op.f('constraint_dpc'))
    )
    op.create_table('federated_identity',
    sa.Column('identity_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('federated_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('federated_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name=op.f('fk404288b92ef007a6')),
    sa.PrimaryKeyConstraint('identity_provider', 'user_id', name=op.f('constraint_40'))
    )
    with op.batch_alter_table('federated_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fedidentity_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fedidentity_feduser'), ['federated_user_id'], unique=False)

    op.create_table('user_federation_mapper_config',
    sa.Column('user_federation_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_federation_mapper_id'], ['user_federation_mapper.id'], name=op.f('fk_fedmapper_cfg')),
    sa.PrimaryKeyConstraint('user_federation_mapper_id', 'name', name=op.f('constraint_fedmapper_cfg_pm'))
    )
    op.create_table('client_session_note',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name=op.f('fk5edfb00ff51c2736')),
    sa.PrimaryKeyConstraint('client_session', 'name', name=op.f('constraint_5e'))
    )
    op.create_table('role_attribute',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['keycloak_role.id'], name=op.f('fk_role_attribute_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_role_attribute_pk'))
    )
    with op.batch_alter_table('role_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_role_attribute'), ['role_id'], unique=False)

    op.create_table('fed_user_credential',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('user_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secret_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credential_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constr_fed_user_cred_pk'))
    )
    with op.batch_alter_table('fed_user_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fu_credential_ru'), ['realm_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fu_credential'), ['user_id', 'type'], unique=False)

    op.create_table('user_role_mapping',
    sa.Column('role_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name=op.f('fk_c4fqv34p1mbylloxang7b1q3l')),
    sa.PrimaryKeyConstraint('role_id', 'user_id', name=op.f('constraint_c'))
    )
    with op.batch_alter_table('user_role_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_role_mapping'), ['user_id'], unique=False)

    op.create_table('realm_smtp_config',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_70ej8xdxgxd0b9hh6180irr0o')),
    sa.PrimaryKeyConstraint('realm_id', 'name', name=op.f('constraint_e'))
    )
    op.create_table('authentication_execution',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('authenticator', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('requirement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('authenticator_flow', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auth_flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('auth_config', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['authentication_flow.id'], name=op.f('fk_auth_exec_flow')),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_auth_exec_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_auth_exec_pk'))
    )
    with op.batch_alter_table('authentication_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_auth_exec_realm_flow'), ['realm_id', 'flow_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_auth_exec_flow'), ['flow_id'], unique=False)

    op.create_table('group_attribute',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("'sybase-needs-something-here'::character varying"), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['keycloak_group.id'], name=op.f('fk_group_attribute_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_group_attribute_pk'))
    )
    with op.batch_alter_table('group_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_group_attr_group'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_group_att_by_name_value'), ['name', sa.literal_column('(value::character varying(250))')], unique=False)

    op.create_table('required_action_provider',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('default_action', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_req_act_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_req_act_prv_pk'))
    )
    with op.batch_alter_table('required_action_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_req_act_prov_realm'), ['realm_id'], unique=False)

    op.create_table('fed_user_group_membership',
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('constr_fed_user_group'))
    )
    with op.batch_alter_table('fed_user_group_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fu_group_membership_ru'), ['realm_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fu_group_membership'), ['user_id', 'group_id'], unique=False)

    op.create_table('federated_user',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('constr_federated_user'))
    )
    op.create_table('resource_policy',
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name=op.f('fk_frsrpp213xcx4wnkog82ssrfy')),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name=op.f('fk_frsrpos53xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('resource_id', 'policy_id', name=op.f('constraint_farsrpp'))
    )
    with op.batch_alter_table('resource_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_res_policy_policy'), ['policy_id'], unique=False)

    op.create_table('event_entity',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details_json', sa.VARCHAR(length=2550), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details_json_long_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_4'))
    )
    with op.batch_alter_table('event_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_time'), ['realm_id', 'event_time'], unique=False)

    op.create_table('user_entity',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_constraint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('federation_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('service_account_client_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('not_before', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_fb')),
    sa.UniqueConstraint('realm_id', 'email_constraint', name=op.f('uk_dykn684sl8up1crfei6eckhd7'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('realm_id', 'username', name=op.f('uk_ru8tt6t700s9v50bu18ws5ha6'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('user_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_service_account'), ['realm_id', 'service_account_client_link'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_email'), ['email'], unique=False)

    op.create_table('databasechangelog',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateexecuted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('orderexecuted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exectype', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('liquibase', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexts', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('labels', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    op.create_table('client_session',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('redirect_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('auth_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('current_action', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], name=op.f('fk_b4ao2vcvat6ukau74wbwtfqo1')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_8'))
    )
    with op.batch_alter_table('client_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_client_session_session'), ['session_id'], unique=False)

    op.create_table('protocol_mapper_config',
    sa.Column('protocol_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['protocol_mapper_id'], ['protocol_mapper.id'], name=op.f('fk_pmconfig')),
    sa.PrimaryKeyConstraint('protocol_mapper_id', 'name', name=op.f('constraint_pmconfig'))
    )
    op.create_table('resource_uris',
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name=op.f('fk_resource_server_uris')),
    sa.PrimaryKeyConstraint('resource_id', 'value', name=op.f('constraint_resour_uris_pk'))
    )
    op.create_table('client_attributes',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk3c47c64beacca966')),
    sa.PrimaryKeyConstraint('client_id', 'name', name=op.f('constraint_3c'))
    )
    with op.batch_alter_table('client_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_client_att_by_name_value'), ['name', sa.literal_column('substr(value, 1, 255)')], unique=False)

    op.create_table('realm',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('access_code_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_action_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_token_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('admin_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('events_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('events_expiration', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('login_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('not_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('password_policy', sa.VARCHAR(length=2550), autoincrement=False, nullable=True),
    sa.Column('registration_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('remember_me', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reset_password_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('social', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ssl_required', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sso_idle_timeout', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sso_max_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_profile_on_soc_login', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verify_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('master_admin_client', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('login_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('internationalization_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('default_locale', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reg_email_as_username', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('admin_events_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('admin_events_details_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('edit_username_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('otp_policy_counter', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_window', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_period', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_digits', sa.INTEGER(), server_default=sa.text('6'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_alg', sa.VARCHAR(length=36), server_default=sa.text("'HmacSHA1'::character varying"), autoincrement=False, nullable=True),
    sa.Column('otp_policy_type', sa.VARCHAR(length=36), server_default=sa.text("'totp'::character varying"), autoincrement=False, nullable=True),
    sa.Column('browser_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('registration_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('direct_grant_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('reset_credentials_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('client_auth_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('offline_session_idle_timeout', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('revoke_refresh_token', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('access_token_life_implicit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('login_with_email_allowed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('duplicate_emails_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('docker_auth_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('refresh_token_max_reuse', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('allow_user_managed_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sso_max_lifespan_remember_me', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sso_idle_timeout_remember_me', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('default_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_4a')),
    sa.UniqueConstraint('name', name=op.f('uk_orvsdmla56612eaefiq6wl5oi'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('realm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_realm_master_adm_cli'), ['master_admin_client'], unique=False)

    op.create_table('resource_server_policy',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('decision_strategy', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('logic', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name=op.f('fk_frsrpo213xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_farsrp')),
    sa.UniqueConstraint('name', 'resource_server_id', name=op.f('uk_frsrpt700s9v50bu18ws5ha6'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('resource_server_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_res_serv_pol_res_serv'), ['resource_server_id'], unique=False)

    op.create_table('user_attribute',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("'sybase-needs-something-here'::character varying"), autoincrement=False, nullable=False),
    sa.Column('long_value_hash', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value_hash_lower_case', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name=op.f('fk_5hrm2vlf9ql5fu043kqepovbr')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_user_attribute_pk'))
    )
    with op.batch_alter_table('user_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_attr_long_values_lower_case'), ['long_value_hash_lower_case', 'name'], unique=False)
        batch_op.create_index(batch_op.f('user_attr_long_values'), ['long_value_hash', 'name'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_attribute_name'), ['name', 'value'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_attribute'), ['user_id'], unique=False)

    op.create_table('fed_user_consent',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('client_storage_provider', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('external_client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constr_fed_user_consent_pk'))
    )
    with op.batch_alter_table('fed_user_consent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fu_consent_ru'), ['realm_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fu_consent'), ['user_id', 'client_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fu_cnsnt_ext'), ['user_id', 'client_storage_provider', 'external_client_id'], unique=False)

    op.create_table('realm_events_listeners',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_h846o4h0w8epx5nxev9f5y69j')),
    sa.PrimaryKeyConstraint('realm_id', 'value', name=op.f('constr_realm_events_listeners'))
    )
    with op.batch_alter_table('realm_events_listeners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_realm_evt_list_realm'), ['realm_id'], unique=False)

    op.create_table('offline_user_session',
    sa.Column('user_session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offline_flag', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_session_refresh', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_session_id', 'offline_flag', name=op.f('constraint_offl_us_ses_pk2'))
    )
    with op.batch_alter_table('offline_user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_offline_uss_preload'), ['offline_flag', 'created_on', 'user_session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_offline_uss_createdon'), ['created_on'], unique=False)
        batch_op.create_index(batch_op.f('idx_offline_uss_by_usersess'), ['realm_id', 'offline_flag', 'user_session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_offline_uss_by_user'), ['user_id', 'realm_id', 'offline_flag'], unique=False)

    op.create_table('fed_user_attribute',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(length=2024), autoincrement=False, nullable=True),
    sa.Column('long_value_hash', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value_hash_lower_case', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constr_fed_user_attr_pk'))
    )
    with op.batch_alter_table('fed_user_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fu_attribute'), ['user_id', 'realm_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('fed_user_attr_long_values_lower_case'), ['long_value_hash_lower_case', 'name'], unique=False)
        batch_op.create_index(batch_op.f('fed_user_attr_long_values'), ['long_value_hash', 'name'], unique=False)

    op.create_table('user_federation_provider',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('changed_sync_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_sync_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_sync', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_1fj32f6ptolw2qy60cd8n01e8')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_5c'))
    )
    with op.batch_alter_table('user_federation_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usr_fed_prv_realm'), ['realm_id'], unique=False)

    op.create_table('identity_provider_mapper',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('idp_alias', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('idp_mapper_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_idpm_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_idpm'))
    )
    with op.batch_alter_table('identity_provider_mapper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_id_prov_mapp_realm'), ['realm_id'], unique=False)

    op.create_table('required_action_config',
    sa.Column('required_action_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('required_action_id', 'name', name=op.f('constraint_req_act_cfg_pk'))
    )
    op.create_table('keycloak_role',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_realm_constraint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_role', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('realm', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm'], ['realm.id'], name=op.f('fk_6vyqfe4cn4wlq8r6kt5vdsj5c')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_a')),
    sa.UniqueConstraint('name', 'client_realm_constraint', name=op.f('UK_J3RWUVD56ONTGSUHOGM184WW2-2'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('keycloak_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_keycloak_role_realm'), ['realm'], unique=False)
        batch_op.create_index(batch_op.f('idx_keycloak_role_client'), ['client'], unique=False)

    op.create_table('redirect_uris',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_1burs8pb4ouj97h5wuppahv9f')),
    sa.PrimaryKeyConstraint('client_id', 'value', name=op.f('constraint_redirect_uris'))
    )
    with op.batch_alter_table('redirect_uris', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_redir_uri_client'), ['client_id'], unique=False)

    op.create_table('realm_default_groups',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_def_groups_realm')),
    sa.PrimaryKeyConstraint('realm_id', 'group_id', name=op.f('constr_realm_default_groups')),
    sa.UniqueConstraint('group_id', name=op.f('con_group_id_def_groups'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('realm_default_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_realm_def_grp_realm'), ['realm_id'], unique=False)

    op.create_table('offline_client_session',
    sa.Column('user_session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('offline_flag', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_storage_provider', sa.VARCHAR(length=36), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False),
    sa.Column('external_client_id', sa.VARCHAR(length=255), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_session_id', 'client_id', 'client_storage_provider', 'external_client_id', 'offline_flag', name=op.f('constraint_offl_cl_ses_pk3'))
    )
    with op.batch_alter_table('offline_client_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_us_sess_id_on_cl_sess'), ['user_session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_offline_css_preload'), ['client_id', 'offline_flag'], unique=False)

    op.create_table('identity_provider_config',
    sa.Column('identity_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['identity_provider_id'], ['identity_provider.internal_id'], name=op.f('fkdc4897cf864c4e43')),
    sa.PrimaryKeyConstraint('identity_provider_id', 'name', name=op.f('constraint_d'))
    )
    op.create_table('realm_attribute',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_8shxd6l3e9atqukacxgpffptw')),
    sa.PrimaryKeyConstraint('name', 'realm_id', name=op.f('constraint_9'))
    )
    with op.batch_alter_table('realm_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_realm_attr_realm'), ['realm_id'], unique=False)

    op.create_table('client_session_auth_status',
    sa.Column('authenticator', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name=op.f('auth_status_constraint')),
    sa.PrimaryKeyConstraint('client_session', 'authenticator', name=op.f('constraint_auth_status_pk'))
    )
    op.create_table('idp_mapper_config',
    sa.Column('idp_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idp_mapper_id'], ['identity_provider_mapper.id'], name=op.f('fk_idpmconfig')),
    sa.PrimaryKeyConstraint('idp_mapper_id', 'name', name=op.f('constraint_idpmconfig'))
    )
    op.create_table('client_scope_role_mapping',
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['client_scope.id'], name=op.f('fk_cl_scope_rm_scope')),
    sa.PrimaryKeyConstraint('scope_id', 'role_id', name=op.f('pk_template_scope'))
    )
    with op.batch_alter_table('client_scope_role_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_role_clscope'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_clscope_role'), ['scope_id'], unique=False)

    op.create_table('realm_localizations',
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('texts', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('realm_id', 'locale', name=op.f('realm_localizations_pkey'))
    )
    op.create_table('admin_event_entity',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('admin_event_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_path', sa.VARCHAR(length=2550), autoincrement=False, nullable=True),
    sa.Column('representation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_admin_event_entity'))
    )
    with op.batch_alter_table('admin_event_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_admin_event_time'), ['realm_id', 'admin_event_time'], unique=False)

    op.create_table('client_node_registrations',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk4129723ba992f594')),
    sa.PrimaryKeyConstraint('client_id', 'name', name=op.f('constraint_84'))
    )
    op.create_table('client_auth_flow_bindings',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('binding_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'binding_name', name=op.f('c_cli_flow_bind'))
    )
    op.create_table('fed_user_consent_cl_scope',
    sa.Column('user_consent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_consent_id', 'scope_id', name=op.f('constraint_fgrntcsnt_clsc_pm'))
    )
    op.create_table('resource_scope',
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name=op.f('fk_frsrpos13xcx4wnkog82ssrfy')),
    sa.ForeignKeyConstraint(['scope_id'], ['resource_server_scope.id'], name=op.f('fk_frsrps213xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('resource_id', 'scope_id', name=op.f('constraint_farsrsp'))
    )
    with op.batch_alter_table('resource_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_res_scope_scope'), ['scope_id'], unique=False)

    op.create_table('resource_server',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('allow_rs_remote_mgmt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('policy_enforce_mode', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('decision_strategy', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_server'))
    )
    op.create_table('realm_enabled_event_types',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_h846o4h0w8epx5nwedrf5y69j')),
    sa.PrimaryKeyConstraint('realm_id', 'value', name=op.f('constr_realm_enabl_event_types'))
    )
    with op.batch_alter_table('realm_enabled_event_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_realm_evt_types_realm'), ['realm_id'], unique=False)

    op.create_table('keycloak_group',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parent_group', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_group')),
    sa.UniqueConstraint('realm_id', 'parent_group', 'name', name=op.f('sibling_names'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('broker_link',
    sa.Column('identity_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('broker_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('broker_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('identity_provider', 'user_id', name=op.f('constr_broker_link_pk'))
    )
    op.create_table('resource_server_resource',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('icon_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('owner_managed_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name=op.f('fk_frsrho213xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_farsr')),
    sa.UniqueConstraint('name', 'owner', 'resource_server_id', name=op.f('uk_frsr6t700s9v50bu18ws5ha6'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('resource_server_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_res_srv_res_res_srv'), ['resource_server_id'], unique=False)

    op.create_table('component_config',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name=op.f('fk_component_config')),
    sa.PrimaryKeyConstraint('id', name=op.f('constr_component_config_pk'))
    )
    with op.batch_alter_table('component_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_compo_config_compo'), ['component_id'], unique=False)

    op.create_table('user_group_membership',
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name=op.f('fk_user_group_user')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('constraint_user_group'))
    )
    with op.batch_alter_table('user_group_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_group_mapping'), ['user_id'], unique=False)

    op.create_table('fed_user_role_mapping',
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'user_id', name=op.f('constr_fed_user_role'))
    )
    with op.batch_alter_table('fed_user_role_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fu_role_mapping_ru'), ['realm_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fu_role_mapping'), ['user_id', 'role_id'], unique=False)

    op.create_table('scope_mapping',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_ouse064plmlr732lxjcn1q5f1')),
    sa.PrimaryKeyConstraint('client_id', 'role_id', name=op.f('constraint_81'))
    )
    with op.batch_alter_table('scope_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_scope_mapping_role'), ['role_id'], unique=False)

    op.create_table('client',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('full_scope_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('not_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('public_client', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bearer_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('management_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('surrogate_auth_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('node_rereg_timeout', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('frontchannel_logout', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('consent_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('service_accounts_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('client_authenticator_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('root_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('registration_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('standard_flow_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('implicit_flow_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('direct_access_grants_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('always_display_in_console', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_7')),
    sa.UniqueConstraint('realm_id', 'client_id', name=op.f('uk_b71cjlbenv945rb6gcon438at'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_client_id'), ['client_id'], unique=False)

    op.create_table('identity_provider',
    sa.Column('internal_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('provider_alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('store_token', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('authenticate_by_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('add_token_role', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('trust_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('first_broker_login_flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('post_broker_login_flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('link_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk2b4ebc52ae5c3b34')),
    sa.PrimaryKeyConstraint('internal_id', name=op.f('constraint_2b')),
    sa.UniqueConstraint('provider_alias', 'realm_id', name=op.f('uk_2daelwnibji49avxsrtuf6xj33'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('identity_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ident_prov_realm'), ['realm_id'], unique=False)

    op.create_table('credential',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secret_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credential_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name=op.f('fk_pfyr0glasqyl0dei3kl69r6v0')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_f'))
    )
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_credential'), ['user_id'], unique=False)

    op.create_table('user_consent',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('client_storage_provider', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('external_client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name=op.f('fk_grntcsnt_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_grntcsnt_pm')),
    sa.UniqueConstraint('client_id', 'client_storage_provider', 'external_client_id', 'user_id', name=op.f('uk_jkuwuvd56ontgsuhogm8uewrt'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_consent'), ['user_id'], unique=False)

    op.create_table('resource_server_scope',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('icon_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name=op.f('fk_frsrso213xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_farsrs')),
    sa.UniqueConstraint('name', 'resource_server_id', name=op.f('uk_frsrst700s9v50bu18ws5ha6'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('resource_server_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_res_srv_scope_res_srv'), ['resource_server_id'], unique=False)

    op.create_table('client_scope_client',
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('default_scope', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'scope_id', name=op.f('c_cli_scope_bind'))
    )
    with op.batch_alter_table('client_scope_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_clscope_cl'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cl_clscope'), ['scope_id'], unique=False)

    op.create_table('realm_required_credential',
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('form_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('input', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('secret', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_5hg65lybevavkqfki3kponh9v')),
    sa.PrimaryKeyConstraint('realm_id', 'type', name=op.f('constraint_92'))
    )
    op.create_table('client_scope',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cli_template')),
    sa.UniqueConstraint('realm_id', 'name', name=op.f('uk_cli_scope'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('client_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_realm_clscope'), ['realm_id'], unique=False)

    op.create_table('resource_attribute',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("'sybase-needs-something-here'::character varying"), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name=op.f('fk_5hrm2vlf9ql5fu022kqepovbr')),
    sa.PrimaryKeyConstraint('id', name=op.f('res_attr_pk'))
    )
    op.create_table('username_login_failure',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('failed_login_not_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_failure', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_ip_failure', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('num_failures', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('realm_id', 'username', name=op.f('CONSTRAINT_17-2'))
    )
    op.create_table('client_initial_access',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remaining_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_client_init_acc_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('cnstr_client_init_acc_pk'))
    )
    with op.batch_alter_table('client_initial_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_client_init_acc_realm'), ['realm_id'], unique=False)

    op.create_table('client_session_role',
    sa.Column('role_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name=op.f('fk_11b7sgqw18i532811v7o2dv76')),
    sa.PrimaryKeyConstraint('client_session', 'role_id', name=op.f('constraint_5'))
    )
    op.create_table('resource_server_perm_ticket',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requester', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('granted_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name=op.f('fk_frsrpo2128cx4wnkog82ssrfy')),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name=op.f('fk_frsrho213xcx4wnkog83sspmt')),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name=op.f('fk_frsrho213xcx4wnkog82sspmt')),
    sa.ForeignKeyConstraint(['scope_id'], ['resource_server_scope.id'], name=op.f('fk_frsrho213xcx4wnkog84sspmt')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_fapmt')),
    sa.UniqueConstraint('owner', 'requester', 'resource_server_id', 'resource_id', 'scope_id', name=op.f('uk_frsr6t700s9v50bu18ws5pmt'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('associated_policy',
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('associated_policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['associated_policy_id'], ['resource_server_policy.id'], name=op.f('fk_frsr5s213xcx4wnkog82ssrfy')),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name=op.f('fk_frsrpas14xcx4wnkog82ssrfy')),
    sa.PrimaryKeyConstraint('policy_id', 'associated_policy_id', name=op.f('constraint_farsrpap'))
    )
    with op.batch_alter_table('associated_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_assoc_pol_assoc_pol_id'), ['associated_policy_id'], unique=False)

    op.create_table('user_required_action',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('required_action', sa.VARCHAR(length=255), server_default=sa.text("' '::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name=op.f('fk_6qj3w1jw9cvafhe19bwsiuvmd')),
    sa.PrimaryKeyConstraint('required_action', 'user_id', name=op.f('constraint_required_action'))
    )
    with op.batch_alter_table('user_required_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_reqactions'), ['user_id'], unique=False)

    op.create_table('authentication_flow',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=36), server_default=sa.text("'basic-flow'::character varying"), autoincrement=False, nullable=False),
    sa.Column('top_level', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('built_in', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_auth_flow_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_auth_flow_pk'))
    )
    with op.batch_alter_table('authentication_flow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_auth_flow_realm'), ['realm_id'], unique=False)

    op.create_table('client_session_prot_mapper',
    sa.Column('protocol_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name=op.f('fk_33a8sgqw18i532811v7o2dk89')),
    sa.PrimaryKeyConstraint('client_session', 'protocol_mapper_id', name=op.f('constraint_cs_pmp_pk'))
    )
    op.create_table('client_user_session_note',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name=op.f('fk_cl_usr_ses_note')),
    sa.PrimaryKeyConstraint('client_session', 'name', name=op.f('constr_cl_usr_ses_note'))
    )
    op.create_table('authenticator_config_entry',
    sa.Column('authenticator_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('authenticator_id', 'name', name=op.f('constraint_auth_cfg_pk'))
    )
    op.create_table('user_federation_config',
    sa.Column('user_federation_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_federation_provider_id'], ['user_federation_provider.id'], name=op.f('fk_t13hpu1j94r2ebpekr39x5eu5')),
    sa.PrimaryKeyConstraint('user_federation_provider_id', 'name', name=op.f('constraint_f9'))
    )
    op.create_table('databasechangeloglock',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('lockgranted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lockedby', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('databasechangeloglock_pkey'))
    )
    op.create_table('user_federation_mapper',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('federation_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('federation_mapper_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['federation_provider_id'], ['user_federation_provider.id'], name=op.f('fk_fedmapperpm_fedprv')),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name=op.f('fk_fedmapperpm_realm')),
    sa.PrimaryKeyConstraint('id', name=op.f('constraint_fedmapperpm'))
    )
    with op.batch_alter_table('user_federation_mapper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_usr_fed_map_realm'), ['realm_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_usr_fed_map_fed_prv'), ['federation_provider_id'], unique=False)

    op.create_table('client_scope_attributes',
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['client_scope.id'], name=op.f('fk_cl_scope_attr_scope')),
    sa.PrimaryKeyConstraint('scope_id', 'name', name=op.f('pk_cl_tmpl_attr'))
    )
    with op.batch_alter_table('client_scope_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_clscope_attrs'), ['scope_id'], unique=False)

    op.drop_table('reviews')
    op.drop_table('event_registrations')
    op.drop_table('events')
    # ### end Alembic commands ###
